services:
  postgres:
    image: postgres:16-alpine
    container_name: gymmate-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gymmate
      POSTGRES_PASSWORD: gymmate
      POSTGRES_DB: gymmate
    volumes:
      - gymmate_pg_data:/var/lib/postgresql/data

volumes:
  gymmate_pg_data:
